# fly.toml app configuration file generated for full-stack-open-pokedex-patient-dew-8026 on 2025-07-14T07:20:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'full-stack-open-pokedex-patient-dew-8026'
primary_region = 'iad'

[build]

[env]
  PORT = "3000"

[deploy]
  strategy = "canary"

[processes]
  app = "node app.js"

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
