name: Schedule Health Check
on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/10 * * * *"
jobs:
  health-check:
    name: Health Check
    runs-on: ubuntu-22.04
    steps:
      - name: Check the deployed render service URL
        uses: jtalk/url-health-check-action@v4
        with: 
          url: https://full-stack-open-pokedex-bxqq.onrender.com/health
      - name: Check the deployed fly.io service URL
        uses: jtalk/url-health-check-action@v4
        with: 
          url: https://full-stack-open-pokedex-patient-dew-8026.fly.dev/health