name: Render Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Wait for Render deployment
        uses: bounceapp/render-action@0.12.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 3
          wait: 16000
          sleep: 30000
