name: Render Deploy
on:
  push:
    branches:
      - main
env:
  CONDITION: ${{ contains(join(github.event.commits.*.message, ''), '#skip') }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-22.04
    steps:
        if: ${{ github.event_name == 'push' && env.CONDITION == 'true' }}
      - name: Wait for Render deployment
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          retries: 3
          wait: 16000
          sleep: 30000
